In [0]:
import numpy as np
a = np.arange(0,10)
a[::-2]

array([9, 7, 5, 3, 1])

In [0]:
import numpy as np
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [0]:
import numpy as np
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype=int)
A[3:,:3]
#쉼표 앞에는 행의 시작:끝:증가값, 뒤에는 열의 시작:끝:증가값

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [0]:
import numpy as np
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype=int)
A[:3,:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [0]:
import numpy as np
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype=int)
A[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [0]:
import numpy as np
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype=int)
A[1::2,1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

In [0]:
import numpy as np
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype=int)
A
B = A[1:5,1:5]
B[:]= 0
A#원본이랑 이어진다

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [0]:
import numpy as np
data = np.arange(0,5)
column =data[:,np.newaxis] #행과 열축 바꾸기
column
#row = data[np.newaxis, :] #열과 행 바꾸기
#row

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [0]:
import numpy as np
data = np.arange(5)
data
np.vstack((data,data,data))#행로 데이터 쌓기
#np.hstack((data,data,data))#열으로 데이터 쌓기

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [0]:
import numpy as np
data = np.arange(5)
data = data[:, np.newaxis]
np.hstack((data,data,data))#행으로 데이터 쌓기

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [0]:
import numpy as np
np.identity(5) #대각선이 다 1로 채워진다
np.eye(5, k=1) #앞에 수는 정방행렬의 크기, 대각선 방향으로 아래 위로 이동 음수일때 밑으로 

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [0]:
import numpy as np
np.diag(np.arange(0,20,5)) #0부터 20전까지 5씩 증가

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [0]:
import numpy as np 
x = np.linspace(-1,1,11)
y = np.sin(np.pi *x)
np.round(y,decimals =4) #y값을 소수 4자리에서 반올림 시키겠다
#np.sin(x)**2+np.cos(x)**2
np.add(np.sin(x)**2,np.cos(x)**2) #위의 주석과 같은 역할
#빼기는 substract, 곱하기 multiply, 나누기 divide 나머지 remainder 반올림 round 부호 sign 절대값 abs 지수 power

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
import numpy as np
data = np.arange(1,10).reshape(3,3)#만든 리스트를 3X3행렬로 만듦
data.sum() #안에 데이터의 합을 나타냄
data.sum(axis =0) #열의 합
data.sum(axis = 1) #행의 합


array([ 6, 15, 24])

In [0]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
a<b
np.all(a<b)
np.any(a<b)

In [0]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([0,1,2,3])
if np.all(a<b):
  print("모두 큼")
elif np.any(a<b):
  print("어떤 건 큼")
else:
  print("모두 작다")

모두 작다


In [0]:
def puls(x,position,height, width):
  return height *(x>=position)*(x<=(position + width))
x = np.linspace(-5,5,11)
puls(x,position = -2, height =1, width =5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [0]:
x = np.linspace(-4,4,9)
np.where(x<0,x**2,x**3) #삼항연산자랑 비슷
np.select([x<-1,x<2,x>=2],[x**2,x**3,x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])