In [0]:
import numpy as np
data = np.arange(5)
data = data[:, np.newaxis]
np.hstack((data,data,data))#행으로 데이터 쌓기

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [0]:
import numpy as np
x = np.linspace(-1,1,11)
y = np.sin(np.pi*x)
np.round(y, decimals=4) #반올림 소수점자리

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [0]:
data = np.arange(1,10).reshape(3,3)
data
data.sum(axis = 0)

array([12, 15, 18])

In [0]:
a = np.arange(1,5)
b = np.arange(4,0,-1)
np.any(a<b)
np.all(a<b)


False

In [0]:
x = np.array([-2,-1,0,1,2])
x >0
1*(x>0) #(x>0)는 T/F가 1/0으로 나타난다
x *(x>0)

array([0, 0, 0, 1, 2])

In [0]:
x = np.linspace(-4,4,9)
np.where(x<0,x**2,x**3) #삼항연산자랑 비슷
np.select([x<-1,x<2,x>=2],[x**2,x**3,x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [0]:
import numpy as np
x = np.linspace(-4,4,9)
np.choose([0,0,0,1,1,1,2,2,2], [x**2,x**3,x**4])#저 범위에서 나뉘는 것을 순서대로 ex) 첨에 -4인데 이때는 0으로 가고, 3번째 의 값은 -1인데 이때는 1번째로 간다. 

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [0]:
x = np.linspace(-4,4,9)
np.nonzero(abs(x) >2) #인덱스 번호를 나타냄
x[np.nonzero(abs(x) >2)] #그 인덱스에 해당하는 값을 알고 싶을 때

array([-4., -3.,  3.,  4.])

In [0]:
a= np.unique([1,2,3,3])
b =np.unique([2,3,4,4,5,6,5])
np.in1d(a,b) # 똑같은 값이 있으면 true, 없으면 false로 뜬다
np.in1d(b,a)
np.all(np.in1d(a,b))
np.union1d(a,b) #중복 없이 합집합
np.intersect1d(a,b) #교집합
np.setdiff1d(a,b)#차집합
np.setdiff1d(b,a)
data = np.arange(9).reshape(3,3)
data
np.transpose(data)#행과 열을 변경

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [0]:
A=np.arange(1,7).reshape(2,3)
B=np.arange(1,7).reshape(3,2)
A
B
np.dot(A,B) # A.dot(B)도 가능


array([[22, 28],
       [49, 64]])

In [0]:
A= np.arange(9).reshape(3,3)
A
x = np.arange(3)
x
np.dot(A,x)

array([ 5, 14, 23])