In [0]:
import numpy as np
data = np.array([[1,2],[3,4],[5,6]])
type(data) #numpy.ndarray는 Numpy의 핵심인 다차원 행렬 자료구조 클래스
data.ndim #2 = 차원의 수, 이경우 이차원 배열이라서
data.shape #(3,2) = 행렬의 구조, 이 경우 data는 3행 2열이기 때문에 (3,2)
data.size # 6 =  배열에 있는 전체 원소 개수
data.dtype# dtype('int64') =배열 원소의 데이터 유형
data.nbytes #48 = 데이터 저장에 사용된 바이트 수

48

In [0]:
import numpy as np
data = np.array([1,2,3],dtype = np.int)#array에 있는 자료형을 dtype으로 바꾸겠다
print(data)

[1 2 3]


In [0]:
import numpy as np
data = np.array([1,2,3],dtype = np.float)#array에 있는 자료형을 dtype으로 바꾸겠다
print(data)

[1. 2. 3.]


In [0]:
import numpy as np
data = np.array([1,2,3],dtype = np.complex)#array에 있는 자료형을 dtype으로 바꾸겠다
print(data)

[1.+0.j 2.+0.j 3.+0.j]


In [0]:
import numpy as np
data = np.array([1,2,3],dtype = np.float) 
#array에 있는 int 자료형을 dtype에 있는 float로 바꾸겠다
data.dtype #자료형이 float로 출력 

data = np.array([1,2,3],dtype = np.int) #float로 저장되어있는 자료형을 int로 변환
data.dtype  #타입은 int64
data #정수로 변환되어 있음 
data.astype(np.float) #data를 float형으로 변환

dtype('float64')

In [0]:
d1 = np.array([1,2,3], dtype= float)
d2 = np.array([1,2,3], dtype= complex)
d1+d2 #결과가 복소수형태로 나옴

(d1+d2).dtype #자료형이 복소수임을 알려준다

dtype('complex128')

In [0]:
import numpy as np
x1 = 5.4*np.ones(10) #5.4를 10번 반복, 똑같은 수를 반복
print(x1)
x2 = np.full(10,5.4) #5.4를 10번 반복 
print(x2)


[5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4]
[5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4]


In [0]:
import numpy as np
x1 = np.empty(5)
x1.fill(3)#빈공간에 채워 넣기
print(x1)

[3. 3. 3. 3. 3.]


In [0]:
import numpy as np
np.array([1.,2.,3.,4.,5.,6.,7.,8.,9.,10.])
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
import numpy as np
np.array([1.,2.,3.,4.,5.,6.,7.,8.,9.,10.])
np.logspace(0,2,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [0]:
import numpy as np
x = np.array([-1,0,1])
y = np.array([-2,0,2])
x,y = np.meshgrid(x,y)
x #가로로 값을 입력
y #세로로 값을 입력
# z = (x+y) **2
# z
# np.identity(4) #대각선이 다 1로 채워진다
# np.eye(4, k=1) #앞에 수는 정방행렬의 크기, 대각선 방향으로 아래 위로 이동 음수일때 밑으로 

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [0]:
import numpy as np
a = np.arange(0,11) 
a#0에서 10까지 출력
a[0]
a[-1]
a[1:-1] #1에서 -1까지 나와야함
a[1:-1: 2] # 1에서 -1까지 증가 폭이 2
a[-5:]
a[:5]
a[-1::-2]

array([10,  8,  6,  4,  2,  0])

In [0]:
before=['2019','12','31']
after = list(map(int, before)) #before에 있는 리스트 내용을 int로 변환
after

[2019, 12, 31]

In [0]:
def adder(a,b):
  return a+b

adder(5,7)

#위와 아래는 동일한 연산

(lambda a,b:a+b)(5,7)


12

In [0]:
arr =list(range(1,5))
print(arr)

list(map(lambda a:a+10,arr))

[1, 2, 3, 4]


[11, 12, 13, 14]

In [0]:
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype = int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [0]:
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype = int)
A
A[:,1] #1열만 추출
A[1,:] #1행만 추출
A[:3,:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [0]:
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype = int)

A[3:,:3]

In [0]:
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype = int)

A[::2,::2]

In [0]:
f = lambda m, n:n+10*m
A = np.fromfunction(f,(6,6),dtype = int)
A[1::2,1::3]


array([[11, 14],
       [31, 34],
       [51, 54]])